RecSystems5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("Recommender.urls")),
    path('admin/', admin.site.urls),
]

Recommender/urls.py
from django.urls import path
from . import views

app_name = "Recommender"
urlpatterns = [
    path("", views.index, name="index"),
    path("recommend/user/", views.recommend_user, name="recommend_user"),
    path("recommend/movie/<int:movie_id>/", views.neighbours_recommend, name="neighbours_recommend"),
    path("recommend/movie/", views.semantic_recommend, name="semantic_recommend"),
    path("compute_vecs/", views.compute_synopsis_vecs, name="compute_synopsis_vecs"),
    path("extract_data/drive/", views.extract_drive_data, name="extract_drive_data"),
    path("extract_data/kaggle/", views.extract_kaggle_posters, name="extract_kaggle_posters"),
    path("extract_data/imdb/", views.scrape_imdb_posters, name="extract_imdb_posters"),
    path("extract_data/ratings/", views.import_ratings, name="import_ratings"),

    path("search", views.search, name="search"),
    path("search_db", views.search_db, name="search_db"),
    # change path to a better name
    # also change it in search.html
    path("movierecommendations", views.movie_recommendations, name="movie_recommendations")
]

Recommender/models.py
from django.db import models


class Neighbourhood(models.Model):
    neighbourhood_id = models.IntegerField(primary_key=True)
    movie_ids = models.TextField()
    ratings = models.TextField()
    ratings_counts = models.TextField()


class Movie(models.Model):
    movie_id = models.IntegerField(primary_key=True)
    tmdb_id = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    genres = models.TextField(null=True, blank=True)
    age_rating = models.CharField(max_length=50, null=True, blank=True)
    avg_ratings = models.FloatField(null=True, blank=True)
    num_ratings = models.IntegerField(null=True, blank=True)
    languages = models.TextField(null=True, blank=True)
    actors = models.TextField(null=True, blank=True)
    directors = models.TextField(null=True, blank=True)
    writers = models.TextField(null=True, blank=True)
    release_year = models.IntegerField(null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    runtime = models.IntegerField(null=True, blank=True)
    imdb_link = models.CharField(max_length=500, null=True, blank=True)
    poster = models.CharField(max_length=100, null=True, blank=True)
    imdb_poster = models.CharField(max_length=200, null=True, blank=True)
    youtube_trailer_video_ids = models.TextField(null=True, blank=True)
    synopsis = models.TextField(max_length=5000, null=True)
    synopsis_vec = models.TextField(null=True)
    tmdb_recommendations = models.TextField(null=True, blank=True)
    tmdb_keywords = models.TextField(null=True, blank=True)
    tmdb_popularity = models.FloatField(null=True, blank=True)
    neighbourhood = models.ForeignKey(Neighbourhood, null=True, blank=True, on_delete=models.CASCADE)

    @staticmethod
    def get_base_url() -> str:
        """
        Returns the base url for the movie posters, just append whatever is in the "poster" field.
        """
        return "https://image.tmdb.org/t/p/original"


class User(models.Model):
    user_id = models.IntegerField(primary_key=True)


class Rating(models.Model):
    RATINGS = {
        1: "Extremely Bad",
        1.5: "Very Bad",
        2: "Bad",
        2.5: "Somewhat Bad",
        3: "Neutral",
        3.5: "Somewhat Good",
        4: "Good",
        4.5: "Very Good",
        5: "Extremely Good"
    }
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.FloatField(choices=RATINGS)

Recommender/views.py
import pandas as pd
from django_pandas.io import read_frame
from django.contrib.auth.decorators import user_passes_test
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render
from tqdm import tqdm
from .extract_data import extract_data, GOOGLE_DRIVE_ROOT, extract_posters, POSTERS_CSV_PATH, RATINGS_CSV_PATH
from .models import User, Movie, Rating

from .utils import (scrape_imdb_poster, get_movies_recommendations, compute_synopsis_vec,
                    format_movie_recommendations, evaluate_recommendations)
from .movie_rec_methods import (tqdm_recommendations, gpt_recommendations, year_genre_recommend,
                                neighbours_recommend, semantic_recommend)


def index(request):
    return render(request, "search.html")


@user_passes_test(lambda u: u.is_superuser)
@transaction.atomic
def compute_synopsis_vecs(request):
    force = request.GET.get("force", True)
    movies = Movie.objects.all() if force else Movie.objects.filter(synopsis_vec__isnull=True)
    count = 0
    total = len(movies)
    for movie in movies:
        synopsis = movie.synopsis
        if synopsis is None:
            continue
        movie.synopsis_vec = compute_synopsis_vec(synopsis)
        if movie.synopsis_vec is not None:
            movie.synopsis_vec = movie.synopsis_vec.dumps().hex()
        movie.save()
        count += 1
    return render(request, "success.html", {"context": {"total": total, "count": count}})


@user_passes_test(lambda u: u.is_superuser)
def compute_neighbours_recommend(request):
    force = request.GET.get("force", False)


@user_passes_test(lambda u: u.is_superuser)
@transaction.atomic
def extract_drive_data(request):
    total, created, updated = extract_data(GOOGLE_DRIVE_ROOT)
    return render(request, "success.html", {"context": {"total": total, "created": created, "updated": updated}})


@user_passes_test(lambda u: u.is_superuser)
@transaction.atomic
def extract_kaggle_posters(request):
    total, updated = extract_posters(POSTERS_CSV_PATH)
    return render(request, "success.html", {"context": {"total": total, "updated": updated}})


@user_passes_test(lambda u: u.is_superuser)
def scrape_imdb_posters(request, batch_size: int = 100, safe: bool = True, force: bool = False):
    movies = Movie.objects.all()
    total = len(movies)
    success = 0
    errors = 0
    ignored = 0
    objs = []
    for i, movie in tqdm(enumerate(movies)):
        if not force and movie.imdb_poster:
            ignored += 1
            continue
        if safe and errors >= 100:
            break
        try:
            if not movie.imdb_link:
                print(f"Movie {movie.movie_id} has no IMDB link.")
                errors += 1
                continue
            movie.imdb_poster = scrape_imdb_poster(movie.imdb_link)
            objs.append(movie)
        except Exception as e:
            print(f"Movie {movie.movie_id} encountered exception: {e}")
            errors += 1
            continue
        if len(objs) >= batch_size:
            with transaction.atomic():
                updated = Movie.objects.bulk_update(objs, ["imdb_poster"], batch_size)
                if updated > 0:
                    objs = []
                    success += updated
    with transaction.atomic():
        updated = Movie.objects.bulk_update(objs, ["imdb_poster"], batch_size)
        success += updated
    return render(request, "success.html",
                  {"context": {"total": total, "successful": success, "errors": errors, "ignored": ignored}})


@user_passes_test(lambda u: u.is_superuser)
def import_ratings(request, batch_size: int = 1000):
    df = pd.read_csv(RATINGS_CSV_PATH,
                     usecols=["userId", "movieId", "rating"]).rename(columns={"userId": "user_id",
                                                                              "movieId": "movie_id"})
    with transaction.atomic():
        deleted, _ = Rating.objects.all().delete()
    new_users = []
    new_ratings = []
    created_users = 0
    created_ratings = 0
    total_ratings = df.shape[0]
    for _, item in tqdm(df.iterrows(), total=total_ratings):
        if Movie.objects.filter(movie_id=item["movie_id"]).exists():
            if not User.objects.filter(user_id=item["user_id"]).exists():
                new_users.append(User(user_id=item["user_id"]))
            new_ratings.append(Rating(user_id=item["user_id"], movie_id=item["movie_id"], rating=item["rating"]))
        if len(new_ratings) >= batch_size:
            with transaction.atomic():
                newly_created_users = len(User.objects.bulk_create(new_users,
                                                                   batch_size=batch_size,
                                                                   ignore_conflicts=True)) if len(new_users) > 0 else 0
                newly_created_ratings = len(Rating.objects.bulk_create(new_ratings,
                                                                       batch_size=batch_size,
                                                                       ignore_conflicts=True))
                new_users = [] if newly_created_users > 0 else new_users
                new_ratings = [] if newly_created_ratings > 0 else new_ratings
                created_users += newly_created_users
                created_ratings += newly_created_ratings
    with transaction.atomic():
        created_users += len(User.objects.bulk_create(new_users, batch_size=batch_size, ignore_conflicts=True))
        created_ratings += len(Rating.objects.bulk_create(new_ratings, batch_size=batch_size, ignore_conflicts=True))
    return render(request, "success.html", {"context": {"deleted": deleted,
                                                        "total ratings": total_ratings,
                                                        "users created": created_users,
                                                        "ratings created": created_ratings}})


def recommend_user(request):
    users = set(User.objects.values_list("user_id", flat=True))
    movies = read_frame(Movie.objects.all())
    ratings = pd.DataFrame(list(Rating.objects.values_list("movie_id", "user_id", "rating")),
                           columns=["movie_id", "user_id", "rating"])

    try:
        # Check if user_id is in users
        if int(request.POST["user_id"]) not in users:
            context = {"error": f"User: {request.POST['user_id']} not found"}
            return render(request, "error.html", context)
    except ValueError:
        # user_id is not a number
        context = {"error": f"User id must be a number"}
        return render(request, "error.html", context)
    except Exception as e:
        print(e)
        context = {"error": f"An unexpected error has occurred"}
        return render(request, "error.html", context)

    try:
        user_predictions = get_movies_recommendations(request.POST["user_id"], users, ratings, movies,
                                                      minimum_ratings=3,
                                                      metric="neighbours_average")

        user_predictions = format_movie_recommendations(user_predictions, 20)

        context = {"recommendations": user_predictions.to_dict('records'), "user_id": request.POST['user_id']}
        return render(request, "recommendations.html", context)

    except Exception as e:
        print(e)
        context = {"error": f"An unexpected error has occurred"}
        return render(request, "error.html", context)


def search(request):
    return render(request, "search.html")


def search_db(request):
    # Columns to keep
    items = ["movie_id", "title", "poster"]

    search_term = request.GET["query"]
    offset = int(request.GET["offset"])

    if search_term:
        movies = Movie.objects.filter(title__icontains=search_term)
    else:
        movies = Movie.objects.all()

    movies = movies[offset:offset + 50]
    movies = read_frame(movies)
    movies = movies[items]

    return JsonResponse({"movies": movies.to_dict('records')})


# For 5 different methods of recommendations
# Add methods in movie_rec_methods.py
def movie_recommendations(request):
    if request.method == "POST":
        movie_id = request.POST["movie_id"]

        # Convert this to dict and add to context
        target_movie = Movie.objects.get(movie_id=movie_id)
        target_movie_dict = {
            "title": target_movie.title,
            "year": target_movie.release_year,
            "imdb_poster": target_movie.imdb_poster,
            "avg_ratings": target_movie.avg_ratings,
            "age_rating": target_movie.age_rating,
            "genres": target_movie.genres.replace("[", "").replace("]", "").replace("'", "").split(",") if target_movie.genres else [],
            "actors": ", ".join(target_movie.actors.replace("[", "").replace("]", "").replace("'", "").split(",")[:4]) if target_movie.actors else "",
            "directors": ", ".join(target_movie.directors.replace("[", "").replace("]", "").replace("'", "").split(",")[:4]) if target_movie.directors else "",
            # We can add more data if we want to I guess?
        }

        # TODO: Maybe we can use multiprocess to perform every call in parallel and save a little bit of time

        context = {
            "target_movie": target_movie_dict,
            "recommendations": {
                "TQDM Recommendations": tqdm_recommendations(movie_id),
                "ChatGPT Recommendations": gpt_recommendations(movie_id),
                "Year-Genre-Keywords Recommendations": year_genre_recommend(movie_id, metric="keyword"),
                "Year-Genre-Actor Recommendations": year_genre_recommend(movie_id, metric="actors"),
                "Neighbourhood Recommendations": neighbours_recommend(movie_id),
                "Semantic Similarity Recommendations": semantic_recommend(movie_id, scale=10)
            },
            "metrics": {

Recommender/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'Recommender/style.css' %}">
    <title>Recommender System</title>
</head>
<body class="body-background">
    <div>
        <div  style="font-size:2.0em;">Oops! Something went wrong</div>
        <div style="font-size:1.5em;">
            Error: 
            {% if error %}
                {{ error }}
            {% else %}
                Reason for the error not specified.
            {% endif %}
        </div>
        <button class="btn btn-dark m-5" onclick="history.back()">Go Back</button>
    </div>
</body>
</html>

Recommender/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Jersey+15&display=swap" rel="stylesheet">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'Recommender/style.css' %}">
    <title>Recommender System</title>
</head>
<body class="bd2 body-background">
    <div class="container my-cont mt-5 border-s text-center position-absolute top-50 start-50 translate-middle" style="border:black double 8px">
        <!-- Title -->
        <div class="h1 jersey-15-regular text-start my-h1">Bored?</div>
        <!-- Subtitle -->
        <div class="h3 jersey-15-regular text-start">Enter your ID and get some movie recommendations!</div>
        <!-- Form to receive user_id -->
        <form action="{% url 'Recommender:recommend_user' %}" method="POST">
        {% csrf_token %}
            <div class="input-group mb-3 justify-content-center"> 
                <input type="number" min="0" class="form-control" placeholder="Enter your ID" name="user_id" id="user_id">       
                <button class="btn btn-primary" type="submit" value="Get Recommendations">Unbore yourself!</button>
            </div>
    </form>
    </div>
</body>
</html>

Recommender/templates/recommendations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Jersey+15&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'Recommender/style.css' %}">
    <title>Recommendations</title>
</head>
<body>
{% if recommendations %}
    <div class="container mt-4">
        <div class="row align-items-center gap-3">
            <div class="col-12 header-text text-center">
                {% if user_id %}
                    <h1 class="line jersey-15-regular">Amazing Movie Recommendations for user {{user_id}}</h1>
                {% elif movie_id and movie_title %}
                    <h1 class="line jersey-15-regular">Amazing Movie Recommendations for movie {{movie_title}} ({{ movie_id }})</h1>
                {% else %}
                    <h1 class="line jersey-15-regular">Amazing Movie Recommendations</h1>
                {% endif %}
            </div>
        </div>
    </div>
    {% for recommendation in recommendations %} <!--|slice:":20"-->
    <div class="container mt-4 text-wrap">
        <div class="row mb-3 movie-row">
            <div class="col-1 text-center  align-items-center d-flex justify-content-center">
                <h3 style="color:#BED754; font-size:60px;" class="jersey-15-regular">{{ forloop.counter }}</h3>
            </div>
            <div class="col-2 d-flex align-items-center justify-content-center">
                <!-- Many image-urls are broken, therefore a placeholder is used -->                
                    <img src="{{recommendation.poster}}" onerror="this.onerror=null;this.src='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/660px-No-Image-Placeholder.svg.png?20200912122019'" class="img-thumbnail img-responsive" alt="poster-image">  
            </div>
            <div class="col-5 mt-2">
                <div class="card" style="background-color: #750E21; border: none; color:whitesmoke;">
                    <div class="card-body">
                        <h4 class="card-title" id="titleTest">
                            <!--- Some titles are formatted like "Matrix, The"-->
                            <!--- Just split and move the "the" to the front of title-->
                            {% if recommendation.title|slice:"-3:" == "The" %} 
                                The {{ recommendation.title|slice:": -5" }}
                            {% else %}
                                {{recommendation.title}}
                            {% endif %}
                        {% for i in "12345" %}
                            {%if i|add:"0" <= recommendation.rating|add:"0" %}
                                <i class="fa fa-star checked"></i>
                            {%else%}
                                <i class="fa fa-star"></i>
                            {% endif %}
                        {% endfor %}
                        </h4>
                        <p class="card-text">Description: {{ recommendation.synopsis }}</p>
                    </div>
                </div>
            </div>
            <div class="col-4 mt-2">
                <div class="card mt-3 border-start border-end-0 border-top-0 border-bottom-0 border-warning" style="background-color: #750E21; color:whitesmoke;">
                    <div class="card-body">
                        <p class="card-text">
                            Genres:
                            {% for genre in recommendation.genres %}
                                <span>{{ genre }}</span>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                    {% if recommendation.actors|length %}
                        <p class="card-text">
                            Actors:
                            {% for actor in recommendation.actors|slice:":10" %} <!-- Limit to the first 5 actors -->
                            <!-- The actors list is in the form: "Characted played", "Actor", .. 
                                 Therefore only print the actors name, and skip fictional characters.-->
                                {% if forloop.counter|divisibleby:2 %}
                                    <span>{{ actor }}</span>{% if not forloop.last %}, {% endif %}
                                {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}
                        <p class="card-text">Directors: {{ recommendation.directors|join:", " }}</p>
                        <p class="card-text">{{ metric|title }}: {{ recommendation.rating }}</p>
                        {% if recommendation.ratings_count %}
                        <p class="card-text">Ratings Count: {{ recommendation.ratings_count|floatformat:0 }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
    </div>
    {% endfor %}
    {% else %}
        No recommendations available.    
    {% endif %}
</body>
</html>

Recommender/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Jersey+15&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'Recommender/style.css' %}">
    <title>Recommender System Movie Search</title>
<!-- Had some problems with the style sheet, therefore some local styles here-->
    <style> 
    .results-container {
        max-height: 300px;
        overflow-y: auto;
        border: 1px solid #ddd;
        background-color: white;
        margin-top: 20px;
        padding: 10px;
        color: white;
    }
    
    .movie-item {
        cursor: pointer;
        padding: 10px;
        border-bottom: 1px solid #ccc;
        color: black;
    }
    
    .movie-item:hover {
        background-color: #f1f1f1;
    }
</style>
</head>
<body class="bd2 body-background">
<!----------------------------------------------------->
<div class="container my-cont mt-5 border-s text-center" style="border:black double 8px" id="main_thing">
    <!-- Title -->
    <div class="h1 jersey-15-regular text-start my-h1">Bored?</div>
    <!-- Subtitle -->
    <div class="h3 jersey-15-regular text-start">Search for a movie you like and get some movie recommendations!</div>
    <!-- Form to receive user_id -->
    <form id="form" action="{% url 'Recommender:movie_recommendations' %}" method="POST" onkeypress="return event.keyCode != 13;">
    {% csrf_token %}
        <div class="input-group mb-3 justify-content-center"> 
            <input type="text" class="form-control" placeholder="Search movies" name="searchBar" id="searchBar">
            <!--<button class="btn btn-primary" id="search_btn" type="button">Search</button>-->
            <ul class="mt-5 dropdown-menu w-100" id="results"></ul>
        </div>
    </form>
    <!--<div class="results-container" id="results"></div>-->
    <div id="loadMore" style="display: none;">
        <div id="loadMoreBtn" class="btn btn-secondary" style="cursor: pointer">
            Load More
        </div>
    </div>
</div>
<!----------------------------------------------------->
<!-- LOADING BOX -->
<div class="container my-cont mt-5 border-s text-center" style="border:black double 8px; display:none" id="loading_screen">
        <h1 id="load_text" class="jersey-15-regular"></h1>
</div>


    <script>
        const csrftoken = "{{csrf_token}}";
        let currentDisplayedMovies = 0;

        //const search_btn = document.getElementById("search_btn");
        const searchBar = document.getElementById("searchBar");
        /*search_btn.onclick = async function() {
            showLoading();
            const searchValue = document.getElementById("searchBar").value;
            const response = await fetch(`/search_db?query=${searchValue}&offset=0`);
            const data = await response.json();
            displayMovies(data.movies, false);
        }*/

        searchBar.addEventListener("input", async function() {
            const resultsDiv = document.getElementById("results");
            if (searchBar.value.trim() === '') {
                searchBar.classList.remove('show');
                resultsDiv.classList.remove('show');
                return; // If search bar is empty, do not display anything
            }
            showLoading();
            const searchValue = searchBar.value;
            const response = await fetch(`/search_db?query=${searchValue}&offset=0`);
            const data = await response.json();
            displayMovies(data.movies, false);
        });

        searchBar.addEventListener("keypress", function(event) {
            if (event.key === "Enter") {
                return
            }
        });

        const load_more_btn = document.getElementById("loadMoreBtn");
        load_more_btn.onclick = async function() {
            const searchValue = document.getElementById("searchBar").value;
            const response = await fetch(`/search_db?query=${searchValue}&offset=${currentDisplayedMovies}`);
            const data = await response.json();
            displayMovies(data.movies, true);
        }

       /* window.onload = async function() {
            showLoading();
            const response = await fetch(`/search_db?offset=0&query=`);
            const data = await response.json();
            displayMovies(data.movies, false);
        }*/

        function showLoading() {
            const resultsDiv = document.getElementById("results");
            resultsDiv.innerHTML = '';
        
            const loading = document.createElement("div");
            loading.className = "spinner-border text-primary"; // Bootstrap spinner class
            loading.setAttribute("role", "status");
        
            const srOnly = document.createElement("span");
            srOnly.className = "visually-hidden";
            srOnly.textContent = "Loading...";
        
            loading.appendChild(srOnly);
            resultsDiv.appendChild(loading);
        }

        function displayMovies(movies, append) {
            const resultsDiv = document.getElementById("results");

            if (!append) {
                currentDisplayedMovies = movies.length;
                resultsDiv.innerHTML = '';
            } else {
                currentDisplayedMovies += movies.length;
            }

            // Must be the same as LIMIT in SQL query
            if (movies.length < 50) {
                load_more_btn.style.display = "none";
            } else {
                load_more_btn.style.display = "block";
            }
            if (searchBar.value.trim() === '') {
                searchBar.classList.remove('show');
                resultsDiv.classList.remove('show');
                return; // If search bar is empty, do not display anything
            }

            // Adding search result movies
            resultsDiv.innerHTML = '';

            movies.forEach(movie => {
                const movieNode = document.createElement("li");
                movieNode.classList.add("dropdown-item", "movie-item");
                movieNode.style.cursor = "pointer";
                movieNode.textContent = movie.title;

                movieNode.onclick = async function(e) {
                    const form = document.getElementById('form');
                    const movieIdField = document.createElement('input');
                    movieIdField.setAttribute('type', 'hidden');
                    movieIdField.setAttribute('name', "movie_id");
                    movieIdField.setAttribute('value', movie.movie_id);
                    form.appendChild(movieIdField);
                    const tmp = document.getElementById('main_thing');
                    const tmp2 = document.getElementById('loading_screen');
                    const tmp3 = document.getElementById('load_text');

                    tmp3.innerHTML = "Loading recommendations for: " + movie.title;
                    tmp2.style.display = "block";

                    tmp.style.display = "none";
                    form.submit();
                }
    
                //const title = document.createElement("p")
                //title.textContent = movie.title
    
                //movieNode.appendChild(title)
                //resultsDiv.appendChild(movieNode)
                resultsDiv.appendChild(movieNode);

                if (movies.length > 0) {
                    searchBar.classList.add('show');
                    resultsDiv.classList.add('show');
                } else {
                    searchBar.classList.remove('show');
                    resultsDiv.classList.remove('show');
                }
            })
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybAujNt3VQmTzt/8A4K37J3bcYIBK7J0TVGlzI8R92QrrsyLr" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-gE5E0FXvY1yqkXpbhrbyOeSNjRzA8VdIiQao1Ayg0iwxGtBaW4XdvwwJN6J9HdWr" crossorigin="anonymous"></script>
</body>
</html>

Recommender/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'Recommender/style.css' %}">
    <title>Recommender System</title>
</head>
<body class="body-background">
    <div>
        <div  style="font-size:2.0em;">Operation completed successfully.</div>
        <div style="font-size:1.5em;">
            {% for key, val in context.items %}
            {{ key|title }}: {{ val }}<br>
            {% endfor %}
        </div>
    </div>
</body>
</html>